force-app/main/default/objects/Sample_Lab_Request__c/Sample_Lab_Request__c.object-meta.xml
<CustomObject>
    <label>Sample/Drawdown Requests</label>
    <nameField>
        <displayFormat>SLR-{00000000}</displayFormat>
        <label>Sample/Lab Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample/Drawdown Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Lab_Request__c/fields/Custom_Letter__c.field-meta.xml
<CustomField>
    <fullName>Custom_Letter__c</fullName>
    <label>Custom Letter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request__c/fields/Customer_UPS_FedEx__c.field-meta.xml
<CustomField>
    <fullName>Customer_UPS_FedEx__c</fullName>
    <label>Customer UPS/FedEx #:</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request__c/fields/Ship_Via__c.field-meta.xml
<CustomField>
    <fullName>Ship_Via__c</fullName>
    <label>Ship Via</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FedEx - Ground</fullName>
                <default>true</default>
                <label>FedEx - Ground</label>
            </value>
            <value>
                <fullName>FedEx - 2 Day</fullName>
            </value>
            <value>
                <fullName>FedEx - Express Saver (3 Day)</fullName>
            </value>
            <value>
                <fullName>FedEx - First Overnight (by 8:00 AM)</fullName>
            </value>
            <value>
                <fullName>FedEx - Ground (Canada Only)</fullName>
            </value>
            <value>
                <fullName>FedEx - International Economy</fullName>
            </value>
            <value>
                <fullName>FedEx - International Priority</fullName>
            </value>
            <value>
                <fullName>FedEx - Overnight Priority (AM - by noon)</fullName>
            </value>
            <value>
                <fullName>FedEx - Standard Overnight (by 3:00 PM)</fullName>
            </value>
            <value>
                <fullName>FLEXcon BV / Air-shipment</fullName>
            </value>
            <value>
                <fullName>FLEXcon BV / Container</fullName>
            </value>
            <value>
                <fullName>FLEXcon Canada / Truck</fullName>
            </value>
            <value>
                <fullName>FLEXcon Glenrothes / Air-shipment</fullName>
            </value>
            <value>
                <fullName>FLEXcon Glenrothes / Container</fullName>
            </value>
            <value>
                <fullName>Inter-Office Mail</fullName>
            </value>
            <value>
                <fullName>UPS - 2 Day Air</fullName>
            </value>
            <value>
                <fullName>UPS - 3 Day Air - Select</fullName>
            </value>
            <value>
                <fullName>UPS - Expedited (Foreign)</fullName>
            </value>
            <value>
                <fullName>UPS - Express (Foreign)</fullName>
            </value>
            <value>
                <fullName>UPS - Ground Residential</fullName>
            </value>
            <value>
                <fullName>UPS - Next Day Air - Early AM</fullName>
            </value>
            <value>
                <fullName>UPS - Next Day Air - Saver (after noon)</fullName>
            </value>
            <value>
                <fullName>UPS - Next Day Air - (before noon)</fullName>
            </value>
            <value>
                <fullName>UPS - Standard (Foreign - Canada Only)</fullName>
            </value>
            <value>
                <fullName>UPS Ground -Com</fullName>
            </value>
            <value>
                <fullName>US Postal Service - First Class</fullName>
            </value>
            <value>
                <fullName>Will Pick Up</fullName>
            </value>
            <value>
                <fullName>Sample - Inter-mail Office 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request__c/fields/Special_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Special_Instructions__c</fullName>
    <description>Requested by the team to track special instructions</description>
    <label>Special Instructions</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Add sample coming from lab</fullName>
            </value>
            <value>
                <fullName>Add sample coming from business team</fullName>
            </value>
            <value>
                <fullName>Add customized letter being sent via interoffice/email</fullName>
            </value>
            <value>
                <fullName>Add business card</fullName>
            </value>
            <value>
                <fullName>Other instructions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Inter-Company Delivery Completed</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request_Products__c/Sample_Lab_Request_Products__c.object-meta.xml
<CustomObject>
    <label>Sample/Lab Request Products</label>
    <nameField>
        <displayFormat>SLRP-{00000000}</displayFormat>
        <label>Sample/Lab Request Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample/Lab Request Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Lab_Request_Products__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MASSACHUSETTS</fullName>
            </value>
            <value>
                <fullName>NEBRASKA</fullName>
            </value>
            <value>
                <fullName>CALIFORNIA</fullName>
            </value>
            <value>
                <fullName>KANSAS</fullName>
            </value>
            <value>
                <fullName>PENNSYLVANIA</fullName>
            </value>
            <value>
                <fullName>MINNESOTA</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request_Products__c/fields/Sample_Lab_Request__c.field-meta.xml
<CustomField>
    <fullName>Sample_Lab_Request__c</fullName>
    <label>Sample/Lab Request</label>
    <referenceTo>Sample_Lab_Request__c</referenceTo>
    <relationshipLabel>Sample/Lab Request Products</relationshipLabel>
    <relationshipName>Sample_Lab_Request_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request_Products__c/fields/Sample_Product__c.field-meta.xml
<CustomField>
    <fullName>Sample_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sample Product</label>
    <referenceTo>Sample_Products__c</referenceTo>
    <relationshipLabel>Sample/Lab Request Products</relationshipLabel>
    <relationshipName>Sample_Lab_Request_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Products__c/Sample_Products__c.object-meta.xml
<CustomObject>
    <label>Sample Products</label>
    <nameField>
        <label>Sample Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sample Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Products__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sample</fullName>
                <label>Samples</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Products__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UL</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>PV</fullName>
            </value>
            <value>
                <fullName>PI,UL</fullName>
            </value>
            <value>
                <fullName>PP,UL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Products__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sample_Products__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Products__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VBS</fullName>
            </value>
            <value>
                <fullName>Legacy</fullName>
            </value>
            <value>
                <fullName>Capabilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SampleRequestProductsAuraControllerTest.cls
/////***** Test class for SampleRequestProductsAuraController ****////

@isTest
public class SampleRequestProductsAuraControllerTest 
{
    static testMethod void getTest() {
        test.startTest();
        
        Sample_Products__c sProd = new Sample_Products__c();
        sProd.Name = 'Test Sample Product';
        sProd.Category__c = 'Sample';
        sProd.Location__c = 'CANADA';
        sProd.Market__c = 'UL';
        sProd.Notes__c = 'This is test product. created for testing code coverage.';
        sProd.Type__c = 'VBS';
        insert sProd;
        
        Sample_Lab_Request__c slReq = new Sample_Lab_Request__c();
        slReq.Status__c = 'New';
        slReq.Ship_Via__c = 'UPS';
        slReq.Customer_UPS_FedEx__c = 'cust fedEx';
        slReq.Custom_Letter__c = 'Yes';
        slReq.Reason__c = 'Test record';
        slReq.Street__c = 'street';
        slReq.City__c = 'city';
        slReq.State__c = 'state';
        slReq.Country__c = 'country';
        insert slReq;
        
        Sample_Lab_Request_Products__c sLReqPrd = new Sample_Lab_Request_Products__c();
        sLReqPrd.Sample_Lab_Request__c = slReq.Id;
        sLReqPrd.Sample_Product__c = sProd.Id;
        sLReqPrd.Quantity__c = 9;
        sLReqPrd.Size__c = 'size';
        sLReqPrd.Location__c = 'CANADA';
        sLReqPrd.Special_Instructions__c = 'test record';
        insert sLReqPrd;
        
        System.assert(SampleRequestProductsAuraController.getLineItems(slReq.Id) != null);
        System.assert(SampleRequestProductsAuraController.getProducts(sProd.Category__c, sProd.Name) != null);
        List<String> jsonStr = new List<String>();
        jsonStr.add(sProd.Id);
        String lineItemsString = JSON.serialize(jsonStr);
        SampleRequestProductsAuraController.add(slReq.Id, lineItemsString);
        
        sLReqPrd.Quantity__c = 99;
        String slReqProdStr = JSON.serialize(sLReqPrd);
        SampleRequestProductsAuraController.updateLI(slReqProdStr);
        SampleRequestProductsAuraController.remove(slReqProdStr);
        
        test.stopTest();
    }
}