force-app/main/default/objects/Sample_Lab_Request__c/Sample_Lab_Request__c.object-meta.xml
<CustomObject>
    <label>Sample/Drawdown Requests</label>
    <nameField>
        <displayFormat>SLR-{00000000}</displayFormat>
        <label>Sample/Lab Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample/Drawdown Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Lab_Request_Products__c/Sample_Lab_Request_Products__c.object-meta.xml
<CustomObject>
    <label>Sample/Lab Request Products</label>
    <nameField>
        <displayFormat>SLRP-{00000000}</displayFormat>
        <label>Sample/Lab Request Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample/Lab Request Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Lab_Request_Products__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MASSACHUSETTS</fullName>
            </value>
            <value>
                <fullName>NEBRASKA</fullName>
            </value>
            <value>
                <fullName>CALIFORNIA</fullName>
            </value>
            <value>
                <fullName>KANSAS</fullName>
            </value>
            <value>
                <fullName>PENNSYLVANIA</fullName>
            </value>
            <value>
                <fullName>MINNESOTA</fullName>
            </value>
            <value>
                <fullName>CANADA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request_Products__c/fields/Product_Text__c.field-meta.xml
<CustomField>
    <fullName>Product_Text__c</fullName>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request_Products__c/fields/S_No__c.field-meta.xml
<CustomField>
    <fullName>S_No__c</fullName>
    <label>S.No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request_Products__c/fields/Sample_Lab_Request__c.field-meta.xml
<CustomField>
    <fullName>Sample_Lab_Request__c</fullName>
    <label>Sample/Lab Request</label>
    <referenceTo>Sample_Lab_Request__c</referenceTo>
    <relationshipLabel>Sample/Lab Request Products</relationshipLabel>
    <relationshipName>Sample_Lab_Request_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request_Products__c/fields/Sample_Product__c.field-meta.xml
<CustomField>
    <fullName>Sample_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sample Product</label>
    <referenceTo>Sample_Products__c</referenceTo>
    <relationshipLabel>Sample/Lab Request Products</relationshipLabel>
    <relationshipName>Sample_Lab_Request_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request_Products__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sample_Products__c/Sample_Products__c.object-meta.xml
<CustomObject>
    <label>Sample Products</label>
    <nameField>
        <label>Sample Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sample Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Products__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sample</fullName>
                <label>Samples</label>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Products__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UL</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PP</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>PV</fullName>
            </value>
            <value>
                <fullName>PI,UL</fullName>
            </value>
            <value>
                <fullName>PP,UL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Products__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Products__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VBS</fullName>
            </value>
            <value>
                <fullName>Legacy</fullName>
            </value>
            <value>
                <fullName>Capabilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SampleRequestProductsAuraController.cls
/*
* @author naveen
* @date 05/09/18 
* @description 
* @Change History
*
*   Tag         Author              Date         Incident No.   Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0       naveen            05/09/18                                        Initial Version 
* *****************************************************************************************************************/
public with sharing class SampleRequestProductsAuraController {
    @AuraEnabled
    public static String getLineItems(String parentId) {
        SampleRequestMainWrapper srm = new SampleRequestMainWrapper();

        for (Sample_Lab_Request_Products__c slrp : [
                SELECT Id, S_No__c, Product_Text__c, Sample_Product__c, Sample_Product__r.Name, Unit_Price__c, UOM__c,
                        Sample_Product__r.Category__c, Location__c, Size__c, Quantity__c, Sample_Lab_Request__c
                FROM Sample_Lab_Request_Products__c
                WHERE Sample_Lab_Request__c = :parentId
                ORDER BY S_No__c ASC
        ]) {
            if (slrp.Sample_Product__r.Category__c == 'Sample') {
                srm.SampleList.add(slrp);
            } else if (slrp.Sample_Product__r.Category__c == 'Marketing') {
                srm.MarketingList.add(slrp);
            } else if (slrp.Sample_Product__r.Category__c == 'Other') {
                srm.OtherList.add(slrp);
            }
        }
        return JSON.serialize(srm);
    }
    @AuraEnabled
    public static String getProducts(String category, String searchString) {
        searchString = '%' + searchString + '%';
        System.debug(category);
        System.debug(searchString);
        List<Sample_Products__c> sampleProducts = new List<Sample_Products__c> ();
        sampleProducts.addAll([
                SELECT Id, Name, Category__c, Location__c, Market__c, Product__c, Size__c, Type__c, UOM__c, Unit_Price__c
                FROM Sample_Products__c
                WHERE Category__c = :category
                AND Name LIKE :searchString
        ]);
        return JSON.serialize(sampleProducts);
    }
    @AuraEnabled
    public static void add(String parentId, String lineItemsString) {
        List<String> productIds = (List<String>) JSON.deserialize (lineItemsString, List<String>.class);
        List<Sample_Lab_Request_Products__c> slrps = new List<Sample_Lab_Request_Products__c> ();
        Map<Id,Sample_Products__c> sampleProducts = new Map<Id,Sample_Products__c>();
        sampleProducts.putAll([
                SELECT Id, Name, Category__c, Location__c, Market__c, Product__c, Size__c, Type__c, UOM__c, Unit_Price__c
                FROM Sample_Products__c
                WHERE Id IN :productIds
        ]);
        for(String productId : productIds) {
            Sample_Products__c sp = sampleProducts.get(productId);
            Sample_Lab_Request_Products__c slrp = new Sample_Lab_Request_Products__c();
            slrp.Sample_Product__c = productId;
            slrp.Sample_Lab_Request__c = parentId;
            slrp.Size__c = sp.Size__c;
            slrp.Product_Text__c = sp.Product__c;
            slrp.Location__c = sp.Location__c;
            slrp.Quantity__c = 0;
            slrp.Unit_Price__c = sp.Unit_Price__c;
            slrp.UOM__c = sp.UOM__c;
            slrps.add(slrp);
        }
        insert slrps;
    }
    @AuraEnabled
    public static void save(String lineItemsString) {
        SampleRequestMainWrapper srm = (SampleRequestMainWrapper) JSON.deserialize(lineItemsString, SampleRequestMainWrapper.class);
        if(srm.SampleList != null && srm.SampleList.size() > 0){
            upsert srm.SampleList;
        }
        if(srm.MarketingList != null && srm.MarketingList.size() > 0){
            upsert srm.MarketingList;
        }
        if(srm.OtherList != null && srm.OtherList.size() > 0){
            upsert srm.OtherList;
        }
    }
    @AuraEnabled
    public static void remove(String removeLIString) {
        Sample_Lab_Request_Products__c slrp = (Sample_Lab_Request_Products__c) JSON.deserialize (removeLIString, Sample_Lab_Request_Products__c.class);
        delete slrp;
    }
    @AuraEnabled
    public static void updateLI(String removeLIString) {
        Sample_Lab_Request_Products__c slrp = (Sample_Lab_Request_Products__c) JSON.deserialize (removeLIString, Sample_Lab_Request_Products__c.class);
        update slrp;
    }
}