force-app/main/default/objects/Sample_Lab_Request__c/Sample_Lab_Request__c.object-meta.xml
<CustomObject>
    <label>Sample/Drawdown Requests</label>
    <nameField>
        <displayFormat>SLR-{00000000}</displayFormat>
        <label>Sample/Lab Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample/Drawdown Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Lab_Request_Products__c/Sample_Lab_Request_Products__c.object-meta.xml
<CustomObject>
    <label>Sample/Lab Request Products</label>
    <nameField>
        <displayFormat>SLRP-{00000000}</displayFormat>
        <label>Sample/Lab Request Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample/Lab Request Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Lab_Request_Products__c/fields/Sample_Lab_Request__c.field-meta.xml
<CustomField>
    <fullName>Sample_Lab_Request__c</fullName>
    <label>Sample/Lab Request</label>
    <referenceTo>Sample_Lab_Request__c</referenceTo>
    <relationshipLabel>Sample/Lab Request Products</relationshipLabel>
    <relationshipName>Sample_Lab_Request_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LabRequestProductsAuraControllerTest.cls
/*
* @author naveen
* @date 01/09/18 
* @description 
* @Change History
*
*   Tag         Author              Date         Incident No.   Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0       naveen            01/09/18                                        Initial Version 
* *****************************************************************************************************************/
@isTest
public with sharing class LabRequestProductsAuraControllerTest {
    @isTest
    public static void test1() {
        Sample_Lab_Request__c slr = new Sample_Lab_Request__c();
        insert slr;
        Sample_Lab_Request_Products__c slrp = new Sample_Lab_Request_Products__c();
        slrp.Sample_Lab_Request__c = slr.Id;
        insert slrp;
        Sample_Lab_Request_Products__c slrp2 = new Sample_Lab_Request_Products__c();
        slrp2.Sample_Lab_Request__c = slr.Id;
        insert slrp2;
        List<Sample_Lab_Request_Products__c> lineItems = LabRequestProductsAuraController.getLineItems(slr.Id);
        String lineItemsString = JSON.serialize(lineItems);
        LabRequestProductsAuraController.save(lineItemsString);
        LabRequestProductsAuraController.add(slr.Id,lineItemsString);
        LabRequestProductsAuraController.remove(JSON.serialize(slrp),lineItemsString);
    }
}