force-app/main/default/objects/Sample_Lab_Request__c/Sample_Lab_Request__c.object-meta.xml
<CustomObject>
    <label>Sample/Drawdown Requests</label>
    <nameField>
        <displayFormat>SLR-{00000000}</displayFormat>
        <label>Sample/Lab Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample/Drawdown Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Lab_Request__c/fields/Special_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Special_Instructions__c</fullName>
    <description>Requested by the team to track special instructions</description>
    <label>Special Instructions</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Add sample coming from lab</fullName>
            </value>
            <value>
                <fullName>Add sample coming from business team</fullName>
            </value>
            <value>
                <fullName>Add customized letter being sent via interoffice/email</fullName>
            </value>
            <value>
                <fullName>Add business card</fullName>
            </value>
            <value>
                <fullName>Other instructions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request_Products__c/Sample_Lab_Request_Products__c.object-meta.xml
<CustomObject>
    <label>Sample/Lab Request Products</label>
    <nameField>
        <displayFormat>SLRP-{00000000}</displayFormat>
        <label>Sample/Lab Request Products Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample/Lab Request Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Lab_Request_Products__c/fields/Coat_Weight__c.field-meta.xml
<CustomField>
    <fullName>Coat_Weight__c</fullName>
    <label>Coat Weight</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request_Products__c/fields/Product_Text__c.field-meta.xml
<CustomField>
    <fullName>Product_Text__c</fullName>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request_Products__c/fields/S_No__c.field-meta.xml
<CustomField>
    <fullName>S_No__c</fullName>
    <label>S.No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request_Products__c/fields/Sample_Lab_Request__c.field-meta.xml
<CustomField>
    <fullName>Sample_Lab_Request__c</fullName>
    <label>Sample/Lab Request</label>
    <referenceTo>Sample_Lab_Request__c</referenceTo>
    <relationshipLabel>Sample/Lab Request Products</relationshipLabel>
    <relationshipName>Sample_Lab_Request_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LabRequestProductsAuraController.cls
/*
* @author naveen
* @date 31/08/18 
* @description 
* @Change History
*
*   Tag         Author              Date         Incident No.   Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0       naveen            31/08/18                                        Initial Version 
* *****************************************************************************************************************/
public with sharing class LabRequestProductsAuraController {

    @AuraEnabled
    public static List<Sample_Lab_Request_Products__c> getLineItems(String parentId) {
        List<Sample_Lab_Request_Products__c> lineItems = new List<Sample_Lab_Request_Products__c> ();
        lineItems.addAll([
                SELECT Id, S_No__c, Product_Text__c, Coat_Weight__c, Quantity__c, Size__c, Special_Instructions__c
                FROM Sample_Lab_Request_Products__c
                WHERE Sample_Lab_Request__c = :parentId
                ORDER BY S_No__c ASC
        ]);
        integer i = 0;
        for(Sample_Lab_Request_Products__c slrp : lineItems) {
            slrp.S_No__c = i;
            i++;
        }
        return lineItems;
    }
    @AuraEnabled
    public static void save(String lineItemsString) {
        List<Sample_Lab_Request_Products__c> lineItems = (List<Sample_Lab_Request_Products__c>) JSON.deserialize(lineItemsString, List<Sample_Lab_Request_Products__c>.class);
        upsert lineItems;
    }
    @AuraEnabled
    public static List<Sample_Lab_Request_Products__c> add(String parentId, String lineItemsString) {
        List<Sample_Lab_Request_Products__c> lineItems = (List<Sample_Lab_Request_Products__c>) JSON.deserialize(lineItemsString, List<Sample_Lab_Request_Products__c>.class);
        lineItems.add(new Sample_Lab_Request_Products__c(S_No__c = lineItems.size(), Sample_Lab_Request__c = parentId));
        return lineItems;
    }
    @AuraEnabled
    public static List<Sample_Lab_Request_Products__c> remove(String removeLIString, String lineItemsString) {
        System.debug(removeLIString);
        Sample_Lab_Request_Products__c removeli = (Sample_Lab_Request_Products__c) JSON.deserialize(removeLIString, Sample_Lab_Request_Products__c.class);
        List<Sample_Lab_Request_Products__c> lineItems = (List<Sample_Lab_Request_Products__c>) JSON.deserialize(lineItemsString, List<Sample_Lab_Request_Products__c>.class);
        List<Sample_Lab_Request_Products__c> newLineItems = new List<Sample_Lab_Request_Products__c> ();
        List<Sample_Lab_Request_Products__c> delLineItems = new List<Sample_Lab_Request_Products__c> ();
        if (lineItems.size() > 1) {
            for (Sample_Lab_Request_Products__c slrp : lineItems) {
                if ((slrp.Id != NULL && slrp.Id == removeli.Id) || slrp.S_No__c == removeli.S_No__c) {
                    if (slrp.Id != NULL)
                        delLineItems.add(slrp);
                } else {
                    newLineItems.add(slrp);
                }
            }
            if (delLineItems.size() > 0)
                delete delLineItems;
            return newLineItems;
        } else {
            return lineItems;
        }

    }
}