force-app/main/default/objects/Account/fields/CUSNO__c.field-meta.xml
<CustomField>
    <fullName>CUSNO__c</fullName>
    <externalId>true</externalId>
    <label>NA Customer Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Type__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Break-Fix</fullName>
            </value>
            <value>
                <fullName>Change Request</fullName>
            </value>
            <value>
                <fullName>Product Problem/Technical Guidance</fullName>
                <color>#33FF33</color>
                <label>Product Related</label>
            </value>
            <value>
                <fullName>Question</fullName>
            </value>
            <value>
                <fullName>Service Related Issue/Inquiry</fullName>
                <color>#FF0000</color>
                <default>true</default>
                <label>Service Related</label>
            </value>
            <value>
                <fullName>Training Request</fullName>
            </value>
            <value>
                <fullName>Workmanship</fullName>
                <isActive>false</isActive>
                <label>Workmanship</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseTriggerHelperTest.cls
/*
* @author naveen
* @date 06/09/18 
* @description 
* @Change History
*
*   Tag         Author              Date         Incident No.   Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0       naveen            06/09/18                                        Initial Version 
* *****************************************************************************************************************/
@isTest
public with sharing class CaseTriggerHelperTest {
    @isTest
    public static void caseAssignmentTest () {
        Account acc = new Account ();
        acc.Name = 'Test';
        acc.CUSNO__c = '12312';
        acc.BillingCity = 'LA';
        acc.BillingCountry = 'United States';
        //acc.BillingCountryCode = '94203';
        acc.BillingState = 'Alaska';
        acc.BillingStreet = '1st Ave';
        acc.BillingPostalCode = '1234';
        insert acc;
        
        AccountTeamMember atm = new AccountTeamMember();
        atm.UserId = userInfo.getUserId();
        atm.AccountId = acc.Id;
        atm.TeamMemberRole = 'Technical Service Rep';
        insert atm;
        
        Case cs = new Case();
        cs.AccountId = acc.Id;
        cs.Case_Type__c = 'Service Related Issue/Inquiry';
        insert cs;
        
        
    }
    @isTest
    public static void caseAssignmentTest2 () {
        Account acc = new Account ();
        acc.Name = 'Test';
        acc.CUSNO__c = '12312';
        acc.BillingCity = 'NY';
        acc.BillingCountry = 'United States';
        //acc.BillingCountryCode = '94203';
        acc.BillingState = 'Alaska';
        acc.BillingStreet = '1st Ave';
        acc.BillingPostalCode = '1234';
        insert acc;
        
        AccountTeamMember atm2 = new AccountTeamMember();
        atm2.UserId = userInfo.getUserId();
        atm2.AccountId = acc.Id;
        atm2.TeamMemberRole = 'Customer Service Rep';
        insert atm2;
        
        Case cs = new Case();
        cs.AccountId = acc.Id;
        cs.Case_Type__c = 'Product Problem/Technical Guidance';
        insert cs;
    }
}