force-app/main/default/objects/Account/fields/CUSNO__c.field-meta.xml
<CustomField>
    <fullName>CUSNO__c</fullName>
    <externalId>true</externalId>
    <label>NA Customer Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryType__c.field-meta.xml
<CustomField>
    <fullName>PrimaryType__c</fullName>
    <label>Primary Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Ad Agency</fullName>
            </value>
            <value>
                <fullName>Ad Specifier</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Co-Supplier</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>Former Alliance</fullName>
            </value>
            <value>
                <fullName>Former Direct</fullName>
            </value>
            <value>
                <fullName>Installer</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>POP Producer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Retailer</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SlackOpportunityPublisherTest.cls
@isTest
public class SlackOpportunityPublisherTest {
    
    static testMethod void testPost() {
        Boolean success = true;
        try {
            Account acc = new Account();
        acc.Name = 'Test';
        acc.CUSNO__c = '123';
        acc.ShippingStreet = 'test';
        acc.ShippingCity = 'new york';
        acc.ShippingCountry = 'United States';
        acc.ShippingState = 'Alaska';
        acc.BillingStreet = 'test';
        acc.BillingCity = 'new york';
        acc.BillingCountry = 'United States';
        acc.BillingState = 'Alaska';
        acc.BillingPostalCode = '1234';
        acc.PrimaryType__c = 'Customer';
        insert acc;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'test';
        opp.StageName = 'Proposal';
        opp.AccountId = acc.Id;
        opp.CloseDate = system.today()+1;
        insert opp;
	        SlackOpportunityPublisher.postToSlack(new List<Id> { opp.Id });
        } catch (Exception e) {
            success = false;
        } finally {
	        System.assert(success);
        }
    }

}