force-app/main/default/objects/Account/fields/CUSNO__c.field-meta.xml
<CustomField>
    <fullName>CUSNO__c</fullName>
    <externalId>true</externalId>
    <label>NA Customer Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PrimaryType__c.field-meta.xml
<CustomField>
    <fullName>PrimaryType__c</fullName>
    <label>Primary Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Ad Agency</fullName>
            </value>
            <value>
                <fullName>Ad Specifier</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Co-Supplier</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>Former Alliance</fullName>
            </value>
            <value>
                <fullName>Former Direct</fullName>
            </value>
            <value>
                <fullName>Installer</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>POP Producer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Retailer</fullName>
            </value>
            <value>
                <fullName>Supplier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request__c/Sample_Lab_Request__c.object-meta.xml
<CustomObject>
    <label>Sample/Drawdown Requests</label>
    <nameField>
        <displayFormat>SLR-{00000000}</displayFormat>
        <label>Sample/Lab Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sample/Drawdown Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sample_Lab_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Sample_Lab_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request__c/fields/Custom_Letter__c.field-meta.xml
<CustomField>
    <fullName>Custom_Letter__c</fullName>
    <label>Custom Letter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request__c/fields/Ship_Via__c.field-meta.xml
<CustomField>
    <fullName>Ship_Via__c</fullName>
    <label>Ship Via</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FedEx - Ground</fullName>
                <default>true</default>
                <label>FedEx - Ground</label>
            </value>
            <value>
                <fullName>FedEx - 2 Day</fullName>
            </value>
            <value>
                <fullName>FedEx - Express Saver (3 Day)</fullName>
            </value>
            <value>
                <fullName>FedEx - First Overnight (by 8:00 AM)</fullName>
            </value>
            <value>
                <fullName>FedEx - Ground (Canada Only)</fullName>
            </value>
            <value>
                <fullName>FedEx - International Economy</fullName>
            </value>
            <value>
                <fullName>FedEx - International Priority</fullName>
            </value>
            <value>
                <fullName>FedEx - Overnight Priority (AM - by noon)</fullName>
            </value>
            <value>
                <fullName>FedEx - Standard Overnight (by 3:00 PM)</fullName>
            </value>
            <value>
                <fullName>FLEXcon BV / Air-shipment</fullName>
            </value>
            <value>
                <fullName>FLEXcon BV / Container</fullName>
            </value>
            <value>
                <fullName>FLEXcon Canada / Truck</fullName>
            </value>
            <value>
                <fullName>FLEXcon Glenrothes / Air-shipment</fullName>
            </value>
            <value>
                <fullName>FLEXcon Glenrothes / Container</fullName>
            </value>
            <value>
                <fullName>Inter-Office Mail</fullName>
            </value>
            <value>
                <fullName>UPS - 2 Day Air</fullName>
            </value>
            <value>
                <fullName>UPS - 3 Day Air - Select</fullName>
            </value>
            <value>
                <fullName>UPS - Expedited (Foreign)</fullName>
            </value>
            <value>
                <fullName>UPS - Express (Foreign)</fullName>
            </value>
            <value>
                <fullName>UPS - Ground Residential</fullName>
            </value>
            <value>
                <fullName>UPS - Next Day Air - Early AM</fullName>
            </value>
            <value>
                <fullName>UPS - Next Day Air - Saver (after noon)</fullName>
            </value>
            <value>
                <fullName>UPS - Next Day Air - (before noon)</fullName>
            </value>
            <value>
                <fullName>UPS - Standard (Foreign - Canada Only)</fullName>
            </value>
            <value>
                <fullName>UPS Ground -Com</fullName>
            </value>
            <value>
                <fullName>US Postal Service - First Class</fullName>
            </value>
            <value>
                <fullName>Will Pick Up</fullName>
            </value>
            <value>
                <fullName>Sample - Inter-mail Office 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Inter-Company Delivery Completed</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sample_Lab_Request__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SLRAddressAuraControllerTest.cls
/////***** Test class for SLRAddressAuraController ****////

@isTest
public class SLRAddressAuraControllerTest 
{
    static testMethod void getTest() {
        test.startTest();
        
        Account acc = new Account();
        acc.Name = 'Test';
        acc.CUSNO__c = '123';
        acc.ShippingStreet = 'test';
        acc.ShippingCity = 'new york';
        acc.ShippingCountry = 'United States';
        acc.ShippingState = 'Alaska';
        acc.BillingStreet = 'test';
        acc.BillingCity = 'new york';
        acc.BillingCountry = 'United States';
        acc.BillingState = 'Alaska';
        acc.BillingPostalCode = '1234';
        acc.PrimaryType__c = 'Customer';
        insert acc; 
        
        Sample_Lab_Request__c testSLR = new Sample_Lab_Request__c();
        testSLR.Account__c = Acc.Id;
        testSLR.Status__c = 'New';
        testSLR.Ship_Via__c = 'FedEx - Ground';
        testSLR.Custom_Letter__c = 'No';
        insert testSLR;
        
        List<Sample_Lab_Request__c> newList = new List<Sample_Lab_Request__c>();
        newList.add(testSLR);
        SampleLabRequestTriggerHelper.populateAddressFields(newList);
        
        System.assert(SLRAddressAuraController.getSLRRecord(testSLR.Id) != null);
        testSLR = SLRAddressAuraController.updateSLR(testSLR.Id, 'updatedstreet', 'updatedcity', 'updatedstate', 'updatedcountry');
        System.assert(testSLR.Street__c == 'updatedstreet');
        test.stopTest();
    }
}